### ISSUE TITLE
train.sh脚本文件找不到

### ISSUE THREAD

**Issue by zhaotongdong** [xiezihao123/Third-place-solution-for-cervical-cancer-intelligent-risk-diagnosis#1]
你好，请问您说的train.sh脚本文件在哪里，我没有找到

**Comment by xiezihao123** [comment]
不好意思 突然发现那两个bash文件好像没有导下来，但是可以确定的是，需要训练和测试的模型都在config下面

**Comment by zhaotongdong** [comment]
@xiezihao123 您好，您能提供下train.sh脚本吗。我想看下您是怎么数据生成的，因为只看data_tools文件感觉有点不知道先看哪个，我觉得您写的非常好，所以想学习下

**Comment by xiezihao123** [comment]
实在不好意思， 由于当时天池上面是不能够下载文件的，所以用一个程序把py的内容导下来了，好像bash文件没有导下来

**Comment by zhaotongdong** [comment]
@xiezihao123 所以说现在找不到bash文件了吗，啊，好难受。。。

**Comment by xiezihao123** [comment]
实际上bash文件里面也没有写数据生成的过程。只是写了测试模型如何得到结果。数据生成过程比较繁琐，首先从kfb里面得到ROI(get_image_from_kfb.py)，然后进行冗余切割（image_segment.py）, 这样生成了初步的数据集，然后训练一个模型，在正样本和空图片上面进行检测产生误检，然后再将误检生成新的数据集(readpkl.py, select_posbox.py)。然后生成测试集（test_segment.py），检测之后将坐标返回原图做非极大抑制以及滤除框中框（results_postprocess.py）

**Comment by zhaotongdong** [comment]
@xiezihao123 非常感谢，我再去仔细看看，再次感谢您的开源，对我真的帮助很大。
另外我还有一个问题，您预测的第7类是怎么定义的那，就是在预测的时候不把第7类提交，只提交前6类的检测结果，是这样子吗

**Comment by xiezihao123** [comment]
是的

**Comment by zhaotongdong** [comment]
@xiezihao123 非常感谢，非常感谢
